### ISSUE TITLE
You should not use <Route> or withRouter() outside a <Router>

### ISSUE THREAD

**Issue by jonleopard** [udilia/learn-react-by-building-a-web-app#3]
Hello! Thanks for making this great tutorial. I'm just about finished with the App, but there seems to be an issue when we wrap the Search component with withRouter. Here is the error:

```
You should not use <Route> or withRouter() outside a <Router>

./src/index.js
src/index.js:29
  26 |   );
  27 | };
  28 | 
> 29 | ReactDOM.render(<App />, document.getElementById('root'));
  30 | 
  31 | 
  32 | 
```

This happens when I wrap Search in Search.js:
`export default withRouter(Search);`

I also receive a similar error when I try to use <Link> in the Header component:
```
  26 |   );
  27 | };
  28 | 
> 29 | ReactDOM.render(<App />, document.getElementById('root'));
  30 | 
  31 | 
  32 | 
```
```
You should not use <Link> outside a <Router>

 <Link>
     <img src={Logo} alt="test" width={90} />
 </Link>
```

Thanks!

**Comment by DimiMikadze** [comment]
Hi @jonleopard 

Thanks.

Can you paste whole `src/index.js` file in here?

**Comment by jonleopard** [comment]
Sure!

index.js:
```
import React from 'react';
import ReactDOM from 'react-dom';
import { ThemeProvider } from 'styled-components';
import { BrowserRouter as Router, Route, Switch } from 'react-router-dom';
import theme from './theme';
import Header from './components/Header';
import List from './components/List';
import NotFound from './components/NotFound';
import Detail from './components/Detail';
import globalStyles from './globalStyles.js';

const App = () => {
  return (
    <ThemeProvider theme={theme}>
      <div>
        <Header />
        <Router>
          <Switch>
            <Route exact path="/" component={List} />
            <Route path="/currency/:id" component={Detail} />
            <Route component={NotFound} />
          </Switch>
        </Router>
      </div>
    </ThemeProvider>
  );
};

ReactDOM.render(<App />, document.getElementById('root'));
```
I'm using styled components and styled-system. <ThemeProvider> just gives components access to style properties defined in my theme.js file. Everything else is the same as in your tutorial.

**Comment by DimiMikadze** [comment]
@jonleopard I think you are receiving this error, because you have `<Header />` outside of `<Router>` component and you are using `<Link>` component inside `<Header>` component. place `Header` inside `Router` and i think your issue will get resolved.

**Comment by jonleopard** [comment]
That did the trick! Thank you @DimiMikadze :)

**Comment by JoshMcCullough** [comment]
@jonleopard If you don't want that extra un-needed `<div>`, you can use `<React.Fragment>` instead.
